### ISSUE TITLE
All Golems have Texture Render Bug

### ISSUE THREAD

**Issue by Camawama** [MinecraftModDevelopment/Extra-Golems#73] opened 2021-03-30 19:01 UTC
![image](https://user-images.githubusercontent.com/43620900/113041956-3494ff80-9160-11eb-85fc-8df85d1c0bb4.png)

All Golems in my world have very strange bugs that flip their block texture upside down but not the overlay on that texture. I have tested many golems and they all have the same issue. I am running my Modpack (Vanilla Plus Lite). I only have 100 mods installed. It's a curseforge modpack so you can install it using the import previously created pack. I can't figure out what would cause this. I have no other texturepack enabled, no shaders, nothing.

[VP LITE 1.16.5-1.0.2.zip](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/6231565/VP.LITE.1.16.5-1.0.2.zip)

**Comment by skyjay1** [comment] 2021-03-30 19:02
Duplicate of #72

**Comment by Camawama** [comment] 2021-03-30 19:02
That was very quick.

**Closed as completed by skyjay1** 2021-03-30 19:02 UTC
Labels: duplicate

**Comment by Camawama** [comment] 2021-03-30 19:03
Oh my, It's an APRIL FOOLS PRANK!!! I see....well, it's still the 30th here for us in Minnesota. Have a nice day!
