### ISSUE TITLE
golem texture flipped upside down with face remaining at top

### ISSUE THREAD

**Issue by crafter360** [MinecraftModDevelopment/Extra-Golems#74] opened 2021-04-01 19:54 UTC
when i was going to play on my modded world with the golem mod for some reason the model is messed up and now upside down with the face still where it was. this happened with all golem types pls fix
![golem glitch](https://user-images.githubusercontent.com/69170701/113346925-61960d80-932c-11eb-9848-262459d89ad3.png)

**Comment by williambl** [comment] 2021-04-01 19:55
Duplicate of #72

**Comment by crafter360** [comment] 2021-04-01 19:55
except for regular golems

**Comment by crafter360** [comment] 2021-04-01 19:55
i didnt know it was reported

**Comment by crafter360** [comment] 2021-04-01 19:55
but yeah im having the same issue

**Comment by williambl** [comment] 2021-04-01 19:56
(Check the date)

**Comment by koderian** [comment] 2021-04-01 19:58
https://i.imgur.com/qQu5ijR.png same issue

**Comment by koderian** [comment] 2021-04-02 00:20
Ah, a April Fools joke. My bad. I looked into the config and I was able to disable this.

**Closed as completed** 2021-04-02 02:51 UTC
Labels: duplicate
