### ISSUE TITLE
Upsidedown

### ISSUE THREAD

**Issue by Ahmed100Ahmed** [MinecraftModDevelopment/Extra-Golems#99] opened 2022-03-31 23:24 UTC
The Golems in  Extra Golems Mod are suddenly  Spawning upside down  ... They were fine... Please Help me solve this prblem

**Comment by skyjay1** [comment] 2022-03-31 23:37
Duplicate of #72 
Hint: check the date

**Closed as completed by skyjay1** 2022-03-31 23:37 UTC
Labels: duplicate

**Comment by Ahmed100Ahmed** [comment] 2022-03-31 23:40
> Duplicate of #72 Hint: check the date

Witch date? The Date of my computer is correct

**Comment by skyjay1** [comment] 2022-03-31 23:42
April Fools!

**Comment by skyjay1** [comment] 2022-03-31 23:42
(You can turn it off by disabling "holiday_tweaks" in the config)

**Comment by Ahmed100Ahmed** [comment] 2022-03-31 23:43
But I use the version 11.3.1 of Extra golems mod

**Comment by Ahmed100Ahmed** [comment] 2022-03-31 23:44
> April Fools!

Really???Oh Man

**Comment by Ahmed100Ahmed** [comment] 2022-03-31 23:52
Thanks Man It works ... now I can go to sleep hahaha
