### ISSUE TITLE
19.2.0  Problem with golems

### ISSUE THREAD

**Issue by 48004800** [MinecraftModDevelopment/Extra-Golems#106] opened 2022-08-27 05:58 UTC
First declare that I have not modified the config file
mod:19.2.0
forge:43.1.3
The first problem villagers no longer spawn iron golems
The second problem is that villagers spawn other golems much faster than the normal version
The third problem villagers only produce clay golems
One last question, bedrock golems can be damaged

**Comment by 48004800** [comment] 2022-08-27 06:03
pictures
![2022-08-27_14 01 00](https://user-images.githubusercontent.com/78255094/187017292-d69cdc0e-92e7-46c5-aa0a-c2bb6c24623c.png)
![Uploading 2022-08-27_14.01.00.png…]()

**Comment by skyjay1** [comment] 2022-08-27 22:09
Duplicate of #105

**Closed as completed** 2022-08-28 00:13 UTC
Labels: bug, duplicate
