### ISSUE TITLE
Game crashes when the guide book is opened

### ISSUE THREAD

**Issue by Boazdacatgamer** [MinecraftModDevelopment/Extra-Golems#132] opened 2024-04-14 02:40 UTC
Hi skyjay1,

I downloaded the latest version of this mod for 1.16.5 and I have allocated as much RAM as possible to the Minecraft launcher for Forge, and I have removed all of my other mods to try to fix the issue, but nothing worked. When I right-click on the guide book, my game instantly crashes. Please, please, please fix this. I want to be able to use all aspects of this mod.

Thanks, and get back to me when you can.
![Screenshot 2024-04-13 223821](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/assets/166968300/72a67169-496a-431d-93de-59ee25e07129)
![2024-04-13_22 37 33](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/assets/166968300/584cc53b-d1c4-4b9d-b99b-f1fa7ec93fea)

**Comment by KiriCattus** [comment] 2024-04-14 02:44
You'd be able to get more help if you posted the actual crash report that it says you can open, with this little information as to what the cause is other than two mods and the "latest version" it's about as simple as finding a needle in a haystack, 

crash reports contain the crucial information we need and new versions could release between now and when a developer responds so "latest version" won't help is what I'm saying, so please do share those :)

**Comment by skyjay1** [comment] 2024-04-14 03:43
Duplicate of #111 . Use the latest non-beta 1.16.5 version if you still have issues.

**Closed as completed** 2024-04-14 03:43 UTC
Labels: duplicate, wontfix

**Comment by Boazdacatgamer** [comment] 2024-04-21 23:39
> You'd be able to get more help if you posted the actual crash report that it says you can open, with this little information as to what the cause is other than two mods and the "latest version" it's about as simple as finding a needle in a haystack,
> 
> crash reports contain the crucial information we need and new versions could release between now and when a developer responds so "latest version" won't help is what I'm saying, so please do share those :)

Hi,
Sorry, I wasn't aware. Here's the crash report:
[crash-2024-04-13_22.38.01-client.txt](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/15055623/crash-2024-04-13_22.38.01-client.txt)
