### ISSUE TITLE
I can only conjure a few golems

### ISSUE THREAD

**Issue by EduMelo** [MinecraftModDevelopment/Extra-Golems#91] opened 2021-10-31 14:49 UTC
I'm trying to install this mod to conjure the most recent golems, as netherite and tnt golem.
I installed the mod and placed extragolems-datapack-16.5.2.zip in world datapack folder.

Do I need a resource pack for it works? Quark datapack/resourcepack is necessary for this works?

I'm using 1.16.5 version

**Comment by skyjay1** [comment] 2021-10-31 22:03
You do not need any datapacks unless you are using Quark

**Comment by EduMelo** [comment] 2021-11-01 17:57
I tried without the datapacks and only could conjure golems made of basic materials.
Why can`t I conjure golems of netherite, tnt, bookshelf etc?

**Comment by skyjay1** [comment] 2021-11-02 00:01
I need more information.
What golems are you able to create?
Does the game crash? If so, provide a crash log. If not, provide a picture of how you are constructing the golem. Make sure you are using a Golem Head, not a Carved Pumpkin (unless the config says otherwise).

**Comment by EduMelo** [comment] 2021-11-02 03:49
I tried a clean installation. I'm usign minecraft 1.16.5 version and forge 1.16.5-36.2.8. I copied only the extra-golems jar to mod folder and right now I can`t conjure any of the extra golems. The following image is showing it:
![2021-11-02_04 38 48](https://user-images.githubusercontent.com/104280/139783571-473c1765-2127-4d82-82db-816c3c7b3b64.png)

```
I can spawn the bedrock golem via the egg.
The only error I'm receiving is when I click  in the recipe book. It crashes my game and presents to me this log:

java.lang.NullPointerException: Unexpected error
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:359) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:270) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookEntry.<init>(GolemBookEntry.java:45) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookScreen.initGolemBookEntries(GolemBookScreen.java:147) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookScreen.<init>(GolemBookScreen.java:131) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.EGScreenLoader.loadBookGui(EGScreenLoader.java:19) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.item.GuideBookItem.func_77659_a(GuideBookItem.java:24) ~[?:16.5.2] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.8.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$439/1441410416.call(Unknown Source) [forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:359) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:270) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookEntry.<init>(GolemBookEntry.java:45) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookScreen.initGolemBookEntries(GolemBookScreen.java:147) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookScreen.<init>(GolemBookScreen.java:131) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.EGScreenLoader.loadBookGui(EGScreenLoader.java:19) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.item.GuideBookItem.func_77659_a(GuideBookItem.java:24) ~[?:16.5.2] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['EduMelo'/1078, l='ClientLevel', x=209.68, y=76.13, z=-43.81]]
	Chunk stats: Client Chunk Cache: 841, 482
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,67,-64), Chunk: (at 0,4,0 in 12,-4; contains blocks 192,0,-64 to 207,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3312 game time, 3312 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.8.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$439/1441410416.call(Unknown Source) [forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
```

**Comment by skyjay1** [comment] 2021-11-02 16:15
Duplicate of issue #89

**Closed as completed by skyjay1** 2021-11-02 16:15 UTC
